sudo: false
language: node_js
node_js:
  - "node"

install:
  - npm install -g codecov
script:
  - codecov

deploy:
  provider: heroku
  api_key:
    secure: HEROKU-API-KEY
  app: chatbot-condominio
