sudo: false
language: node_js
node_js:
  - "node"

before_script:
  - npm install
  - npm install -g coveralls

after_success: 
  - npm run coveralls

deploy:
  provider: heroku
  api_key:
    secure: HEROKU-API-KEY
  on:
    tags: true
    all_branches: true
  app: chatbot-condominio
