sudo: false
language: node_js
node_js:
  - "node"

before_script:
  - npm install
  - npm install coveralls

deploy:
  provider: heroku
  api_key:
    secure: HEROKU-API-KEY
  app: chatbot-condominio
